AWSTemplateFormatVersion: '2010-09-09'
Description: '

  Sample SAM Template for s3-lambda-s3 function

  '
Globals:
  Function:
    Timeout: 120
Outputs:
  DynamoDBTableArn:
    Description: The ARN of your DynamoDB Table
    Value:
      Fn::GetAtt:
      - DynamoDBTable
      - Arn
  DynamoDBTableStreamArn:
    Description: The ARN of your DynamoDB Table Stream
    Value:
      Fn::GetAtt:
      - DynamoDBTable
      - StreamArn
  InputS3Bucket:
    Description: Input Bucket name
    Value:
      Ref: InputS3Bucket
  LambdaFunctionARN:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - AddToDynamoLambdaFunction
      - Arn
  LambdaFunctionRole:
    Description: Implicit IAM Role created for the lambda function
    Value:
      Fn::GetAtt:
      - AddToDynamoLambdaFunctionRole
      - Arn
Parameters:
  DynamoDBTableName:
    Default: s3-lambda-dynamo-next
    MinLength: 3
    Type: String
  InputS3BucketName:
    Default: s3-lambda-dynamo-input-bucket-daghan
    MinLength: 3
    Type: String
Resources:
  AddToDynamoLambdaFunction:
    Properties:
      CodeUri: s3://deployment-sam-js10-lambda-dynamo/b2748eaa7c0257b95c0325e4a3c46dd4
      Environment:
        Variables:
          TABLE_NAME:
            Ref: DynamoDBTableName
      Events:
        FileUploadTrigger:
          Properties:
            Bucket:
              Ref: InputS3Bucket
            Events: s3:ObjectCreated:*
          Type: S3
      Handler: app.lambdaHandler
      Policies:
      - S3ReadPolicy:
          BucketName:
            Ref: InputS3BucketName
      - DynamoDBCrudPolicy:
          TableName:
            Ref: DynamoDBTableName
      Runtime: nodejs10.x
    Type: AWS::Serverless::Function
  DynamoDBTable:
    Properties:
      AttributeDefinitions:
      - AttributeName:
          Fn::Sub: ${DynamoDBTableName}_hash
        AttributeType: S
      - AttributeName:
          Fn::Sub: ${DynamoDBTableName}_range
        AttributeType: S
      KeySchema:
      - AttributeName:
          Fn::Sub: ${DynamoDBTableName}_hash
        KeyType: HASH
      - AttributeName:
          Fn::Sub: ${DynamoDBTableName}_range
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName:
        Ref: DynamoDBTableName
    Type: AWS::DynamoDB::Table
  InputS3Bucket:
    Properties:
      BucketName:
        Ref: InputS3BucketName
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
